trigger:
  - main
  - feature/*
  - hotfix/*
  - release/*

# Run the build nightly to ensure our CodeQL and other compliance checks run regularly.
schedules:
  # https://crontab.guru/#42_7_*_*_*
  # 07:42 UTC => 00:42 PST / 23:42 PDT
  - cron: 42 7 * * *
    displayName: Nightly Check build

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*

extends:
  template: /script/pipelines/pipeline-template.yml
  parameters:
    IsReleaseBuild: false
    LinuxPool:
      name: ClientEngine
      demands:
        - ImageOverride -equals client-engine-linux-x86_64
    LinuxARM64Pool:
      name: ClientEngine-ARM64
      demands:
        - ImageOverride -equals client-engine-linux-aarch64
    MacPool:
      vmImage: macos-15
    WindowsPool:
      name: ClientEngine
      demands:
        - ImageOverride -equals client-engine-windows-x86_64
