trigger: none

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*

extends:
  template: /script/pipeline-template.yml
  parameters:
    ReleaseBuild: false
