trigger: none

extends:
  template: /script/pipelines/pipeline-template.yml
  parameters:
    IsReleaseBuild: true
    UseMicrosoftToolchain: true
    LinuxPool:
      name: SDK-RustClientEngine
      demands:
        - ImageOverride -equals client-engine-linux-x86_64
    LinuxARM64Pool:
      name: SDK-RustClientEngine
      demands:
        - ImageOverride -equals client-engine-linux-aarch64
    MacPool:
      vmImage: macos-15
    WindowsPool:
      name: SDK-RustClientEngine
      demands:
        - ImageOverride -equals client-engine-windows-x86_64
