trigger: none

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*

extends:
  template: /script/pipelines/pipeline-template.yml
  parameters:
    IsReleaseBuild: false
    LinuxPool:
      name: ClientEngine
      demands:
        - ImageOverride -equals client-engine-linux-x86_64
    LinuxARM64Pool:
      name: ClientEngine
      demands:
        - ImageOverride -equals client-engine-linux-aarch64
    MacPool:
      vmImage: macos-15
    WindowsPool:
      name: ClientEngine
      demands:
        - ImageOverride -equals client-engine-windows-x86_64
