trigger: none

parameters:
  - name: GoReleaseVersion
    displayName: The version of the Go wrapper package
    type: string

extends:
  template: /script/pipelines/pipeline-template.yml
  parameters:
    IsReleaseBuild: true
    LinuxPool:
      name: SDK-RustClientEngine
      demands:
        - ImageOverride -equals client-engine-linux-x86_64
    MacPool:
      vmImage: macos-15
    WindowsPool:
      name: SDK-RustClientEngine
      demands:
        - ImageOverride -equals client-engine-windows-x86_64
