trigger: none

parameters:
  - name: GoReleaseVersion
    displayName: Go Release Version ('x.y.z', no 'v' or other prefix)
    type: string

extends:
  template: /script/pipelines/pipeline-template.yml
  parameters:
    IsReleaseBuild: true
    GoReleaseVersion: ${{ parameters.GoReleaseVersion }}
    LinuxPool:
      name: SDK-RustClientEngine
      demands:
        - ImageOverride -equals client-engine-linux-x86_64
    MacPool:
      vmImage: macos-15
    WindowsPool:
      name: SDK-RustClientEngine
      demands:
        - ImageOverride -equals client-engine-windows-x86_64
