trigger: none

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*

extends:
  template: /script/pipelines/pipeline-template.yml
  parameters:
    IsReleaseBuild: false
    Pool_x86_64-linux-gnu:
      name: ClientEngine
      demands:
        - ImageOverride -equals client-engine-linux-x86_64
    Pool_x86_64-apple-darwin:
      vmImage: macos-latest
    Pool_aarch64-apple-darwin:
      vmImage: macos-latest
