[package]
name = "azure_data_cosmos_engine"
description = "Azure Cosmos DB Client Engine"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[features]
# We want to keep pyo3 code separate and in the Python module, but if we do that, we can't derive conversion traits like FromPyObject/IntoPyObject in this crate.
# So, we do use pyo3 here, but only for those conversion traits, and it's behind this feature (which is enabled by the python module).
python_conversions = ["dep:pyo3"]

[dev-dependencies]
pretty_assertions = "1.4.1"

# TODO: Move to published dependencies once we've got the API stable.
azure_core = { path = "../../azure-sdk-for-rust/sdk/core/azure_core" }
azure_identity = { path = "../../azure-sdk-for-rust/sdk/identity/azure_identity" }
azure_data_cosmos = { path = "../../azure-sdk-for-rust/sdk/cosmos/azure_data_cosmos", features = ["key_auth"] }
uuid = "1.16.0"
futures = "0.3.31"
tokio = "1.45.0"
