[package]
name = "azure_data_cosmos_engine"
description = "Azure Cosmos DB Client Engine"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[features]
python = ["dep:pyo3", "pyo3/extension-module"]

[dev-dependencies]
pretty_assertions = "1.4.1"
