parameters:
  - name: IsReleaseBuild
    type: boolean
    default: false
  - name: UseMicrosoftToolChain
    type: boolean
    default: false
  - name: LinuxPool
    type: object
  - name: MacPool
    type: object
  - name: WindowsPool
    type: object

variables:
  CONFIGURATION: release
  RUSTFLAGS: "-D warnings"
  GO_VERSION: "1.24.5"
  PY_VERSION: "3.11"
  EMULATORMSIURL: https://aka.ms/cosmosdb-emulator

stages:
  - stage: Validate
    dependsOn: []
    jobs:
      - job: analyze
        displayName: "Analyze and Test"
        pool: ${{ parameters.LinuxPool }}
        steps:
          - template: prep-agent.yml
            parameters:
              IsReleaseBuild: ${{ parameters.IsReleaseBuild }}
          - pwsh: script/check-headers.ps1
            displayName: "Check headers"
          - script: just check
            displayName: "Check formatting and license headers"

      - job: query_correctness
        strategy:
          matrix:
            rust:
              language: "Rust"
              target: "query_test_rust"
              CARGO_BUILD_TARGET: x86_64-pc-windows-msvc
            go:
              language: "Go"
              target: "query_test_go"
              CARGO_BUILD_TARGET: x86_64-pc-windows-gnu # Go requires the GNU build
        displayName: "Run ${{variables.language}} Query Correctness Tests"
        pool: ${{ parameters.WindowsPool }}
        steps:
          - template: prep-agent.yml
            parameters:
              HostIsWindows: true
              IsReleaseBuild: ${{ parameters.IsReleaseBuild }}
              UseMicrosoftToolchain: ${{ parameters.UseMicrosoftToolchain }}

          - template: emulator-setup.yml

          - script: just engine
            displayName: "Build Client Engine"

          - script: just $(target)
            displayName: "Run query tests"

  - stage: Build
    dependsOn: []
    jobs:
      - job: x86_64_pc_windows_msvc
        displayName: "Windows x86_64 MSVC"
        pool: ${{ parameters.WindowsPool }}
        steps:
          - template: /script/pipelines/build-job.yml
            parameters:
              RustTarget: x86_64-pc-windows-msvc
              HostIsWindows: true
              PublishArtifacts: ${{ parameters.IsReleaseBuild }}
              UseMicrosoftToolchain: ${{ parameters.UseMicrosoftToolchain }}

              # Go doesn't support MSVC-built libraries, we'll test it in the x86_64-pc-windows-gnu build
              RunGoTests: false
              VendorForGo: false

      - job: x86_64_pc_windows_gnu
        displayName: "Windows x86_64 GNU"
        pool: ${{ parameters.WindowsPool }}
        steps:
          - template: /script/pipelines/build-job.yml
            parameters:
              RustTarget: x86_64-pc-windows-gnu
              HostIsWindows: true
              PublishArtifacts: ${{ parameters.IsReleaseBuild }}
              UseMicrosoftToolchain: false # There is no internal x86_64-pc-windows-gnu toolchain

      - job: x86_64_linux_gnu
        displayName: "Linux x86_64"
        pool: ${{ parameters.LinuxPool }}
        steps:
          - template: /script/pipelines/build-job.yml
            parameters:
              RustTarget: x86_64-unknown-linux-gnu
              PublishArtifacts: ${{ parameters.IsReleaseBuild }}
              UseMicrosoftToolchain: ${{ parameters.UseMicrosoftToolchain }}

      - job: x86_64_apple_darwin
        displayName: "macOS x86_64"
        pool: ${{ parameters.MacPool }}
        steps:
          - template: /script/pipelines/build-job.yml
            parameters:
              RustTarget: x86_64-apple-darwin
              PublishArtifacts: ${{ parameters.IsReleaseBuild }}
              UseMicrosoftToolchain: ${{ parameters.UseMicrosoftToolchain }}

      - job: aarch64_apple_darwin
        displayName: "macOS aarch64"
        pool: ${{ parameters.MacPool }}
        steps:
          - template: /script/pipelines/build-job.yml
            parameters:
              RustTarget: aarch64-apple-darwin
              PublishArtifacts: ${{ parameters.IsReleaseBuild }}
              UseMicrosoftToolchain: ${{ parameters.UseMicrosoftToolchain }}

              # The job runs on an x86_64 machine, so we can't run tests.
              RunGoTests: false
              RunRustTests: false

  - ${{ if eq(parameters.IsReleaseBuild, true) }}:
      - stage: Package
        dependsOn:
          - Build
        jobs:
          - job: package
            displayName: "Create packages"
            pool: ${{ parameters.LinuxPool }}
            steps:
              - checkout: none
              - download: current
                patterns: "**"
              - bash: |
                  # Move up to the pipeline workspace directory.
                  # The default working directory is in the 's' subdirectory of this one.
                  # See https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=yaml%2Cbrowser#agent-directory-structure for more.
                  cd "$(Pipeline.Workspace)"

                  prepare_package() {
                    local prefix="$1"
                    output_dir=./s/output/$prefix
                    mkdir -p $output_dir
                    echo "Created $output_dir"
                    for dir in $(find . -maxdepth 1 -mindepth 1 -type d -name ${prefix}_\*); do
                      target=$(echo $dir | cut -d'_' -f 2-)
                      source="$dir/libcosmoscx.a"
                      mkdir "$output_dir/$target"
                      echo "Moving $source to $output_dir/$target"
                      mv $source "$output_dir/$target"
                    done
                  }

                  prepare_package "vendored"
              - publish: output
                displayName: "Publish packages"
                artifact: "packages"

      - stage: Stage
        dependsOn:
          - Package
          - Validate
        jobs:
          - job: publish_go
            displayName: "Publish Go Wrapper"
            pool: ${{ parameters.LinuxPool }}
            steps:
              - checkout: self
                fetchTags: true
                persistCredentials: true
              - download: current
                artifact: packages
                patterns: "**"
              - bash: |
                  version=cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "cosmoscx") | .version'
                  tag_name="go/azcosmoscx/v$version"
                  branch_name="azp-release-staging/v$version"
                  echo "##vso[task.setvariable variable=ReleaseVersion]$version"
                  echo "##vso[task.setvariable variable=ReleaseTag]$tag_name"
                  echo "##vso[task.setvariable variable=ReleaseBranch]$branch_name"
              - bash: |
                  echo "Preparing Go wrapper release tag '$(ReleaseTag)'"
                  if git rev-parse -q --verify "refs/tags/$(ReleaseTag)" >/dev/null; then
                    echo "Error: Git tag '$(ReleaseTag)' already exists. Aborting release."
                    exit 1
                  fi

                  git checkout -b "$(ReleaseBranch)"

                  src_dir="$(Pipeline.Workspace)/packages/vendored"
                  dest_dir="./go/azcosmoscx/libcosmoscx-vendor"

                  echo "Creating destination directory '$dest_dir'"
                  mkdir -p "$dest_dir"

                  # Ensure there is at least one subdirectory to copy
                  if ! find "$src_dir" -maxdepth 1 -mindepth 1 -type d -print -quit >/dev/null 2>&1; then
                    echo "No subdirectories found in '$src_dir' to copy."
                    exit 1
                  fi

                  echo "Copying subdirectories from '$src_dir' into '$dest_dir' (subdirs become direct children)"
                  # rsync copies the contents of src_dir into dest_dir, making each top-level subdirectory a direct child
                  rsync -a --chmod=ugo=rwX "$src_dir"/ "$dest_dir"/

                  echo "Copy complete."
                displayName: "Place vendored binaries"
              - bash: |
                  git add go/azcosmoscx/libcosmoscx-vendor
                  git config --global user.name "Azure Pipelines"
                  git config --global user.email "bot@example.com"
                  git commit -m"Updating vendored binaries to $(ReleaseVersion)"

                  # It's OK to force push here. Any time we're running this pipeline, we want to replace any bits in the release branch with the new ones.
                  git push --force origin $(ReleaseBranch)
                displayName: Commit to release staging branch
