# Default config used for local development and PR validation builds.

# Set the linker for ARM64 Linux targets to enable cross-compilation.
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"