#!/usr/bin/env bash
#/ Usage: script/bootstrap
#/
#/ Set up repository dependencies.
#/ Based on the scripts-to-rule-them-all pattern: https://github.com/github/scripts-to-rule-them-all
script_dir=$(dirname "$(readlink -f "$0")")
cd "$script_dir/.."
repo_root="$PWD"

set -euo pipefail

while [[ "$#" -gt 0 ]]; do
    key="$1"
    shift
    case "$key" in -h|--help) 
            grep '^#/' <"$0" | cut -c4-
            exit 0
            ;;
        *) 
            echo "Unknown parameter passed: $1"
            exit 1
            ;;
    esac
done

script/check-deps

printenv | grep "PIP"

# Ensure pip and pipx are installed.
if ! type pip >/dev/null 2>&1; then
    echo "pip is not installed, installing pip..."
    if type python >/dev/null 2>&1; then
        python -m ensurepip
    else
        echo "Python3 is not installed, please install Python3 and try again."
        exit 1
    fi
else
    echo "pip is already installed"
fi

if ! type pipx >/dev/null 2>&1; then
    python -m pip install --user pipx
else
    echo "pipx is already installed"
fi

pipx install maturin

pipx install poetry
poetry config virtualenvs.in-project true

echo "Installing cbindgen..."
cargo install --locked cbindgen@0.29.0

eval "$(poetry -C ./python env activate)"

poetry -C ./python install

echo "Installing addlicense..."
go install github.com/google/addlicense@v1.1.1
