#!/usr/bin/env bash
#/ Usage: script/bootstrap
#/
#/ Set up repository dependencies.
#/ Based on the scripts-to-rule-them-all pattern: https://github.com/github/scripts-to-rule-them-all
script_dir=$(dirname "$(readlink -f "$0")")
cd "$script_dir/.."
repo_root="$PWD"

venv_bindir="$repo_root/.venv/bin"
if [ "$OS" = "Windows_NT" ]; then
    venv_bindir="$repo_root/.venv/Scripts"
fi

while [[ "$#" -gt 0 ]]; do
    key="$1"
    shift
    case "$key" in -h|--help) 
            grep '^#/' <"$0" | cut -c4-
            exit 0
            ;;
        *) 
            echo "Unknown parameter passed: $1"
            exit 1
            ;;
    esac
done

echo "Checking dependencies we don't auto-install..."
script/check-deps

echo "Installing Maturin..."
pipx install maturin

echo "Installing Poetry..."
pipx install poetry
poetry config virtualenvs.in-project true

echo "Installing cbindgen..."
cargo install --locked cbindgen@0.29.0

echo "Activating virtualenv..."
eval "$(poetry -C ./python env activate)"

echo "Installing Python dependencies..."
poetry -C ./python install

echo "Installing addlicense..."
go install github.com/google/addlicense@v1.1.1
