#!/usr/bin/env bash
#/ Usage: script/bootstrap
#/
#/ Set up repository dependencies.
#/ Based on the scripts-to-rule-them-all pattern: https://github.com/github/scripts-to-rule-them-all
script_dir=$(dirname "$(readlink -f "$0")")
cd "$script_dir/.."
repo_root="$PWD"

venv_bindir="$repo_root/.venv/bin"
if [ "$OS" = "Windows_NT" ]; then
    venv_bindir="$repo_root/.venv/Scripts"
fi

use_pipx=false
while [[ "$#" -gt 0 ]]; do
    key="$1"
    shift
    case "$key" in
        --use-pipx)
            use_pipx=true
            ;;
        -h|--help) 
            grep '^#/' <"$0" | cut -c4-
            exit 0
            ;;
        *) 
            echo "Unknown parameter passed: $1"
            exit 1
            ;;
    esac
done

echo "Checking dependencies we don't auto-install..."
script/check-deps

echo "Creating virtualenv and installing modules..."
python3 -m venv ./.venv
$venv_bindir/pip install -r ./python/dev-requirements.txt

echo "Installing Maturin..."
if $use_pipx; then
    pipx install maturin
else
    cargo install --locked maturin
fi

echo "Installing cbindgen..."
cargo install --locked cbindgen