#!/usr/bin/env bash
#/ Usage: script/check-headers
#/
#/ Validates that the cosmoscx.h header file is up-to-date.
script_dir=$(dirname "$(readlink -f "$0")")
cd "$script_dir/.."
repo_root="$PWD"

GEN_PATH=`mktemp`
trap 'rm -f ${GEN_PATH}' EXIT
COSMOSCX_HEADER_PATH=${GEN_PATH} make _generate_headers

echo "Comparing headers..."
if diff "${repo_root}/include/cosmoscx.h" "${GEN_PATH}"; then
    echo "Header file 'include/cosmoscx.h' is up-to-date"
else
    echo "Header file 'include/cosmoscx.h' is out-of-date. Run 'make headers' to update."
    exit 1
fi

if diff "${repo_root}/go/azcosmoscx/include/cosmoscx.h" "${GEN_PATH}"; then
    echo "Header file 'go/azcosmoscx/include/cosmoscx.h' is up-to-date"
else
    echo "Header file 'go/azcosmoscx/include/cosmoscx.h' is out-of-date. Run 'make headers' to update."
    exit 1
fi