#!/usr/bin/env bash
#/ Usage: script/docs-server
#/
#/ Launches a local server displaying the Rust API documentation.
script_dir=$(dirname "$(readlink -f "$0")")
cd "$script_dir/.."
repo_root="$PWD"

cargo watch -s "RUSTDOCFLAGS=\"--enable-index-page -Z unstable-options\" cargo +nightly doc --document-private-items --all-features --workspace --no-deps" -s "http-server --index --port 8080 ./target/doc"