#!/usr/bin/env bash
#/ Usage: script/fmt
#/
#/ Run all formatters for the repository
script_dir=$(dirname "$(readlink -f "$0")")
cd "$script_dir/.."
repo_root="$PWD"

check=false
fix=false
while [[ "$#" -gt 0 ]]; do
    key="$1"
    shift
    case "$key" in 
        -c|--check) 
            check=true
            ;;
        -f|--fix) 
            fix=true
            ;;
        -h|--help) 
            grep '^#/' <"$0" | cut -c4-
            exit 0
            ;;
        *) 
            echo "Unknown parameter passed: $1"
            exit 1
            ;;
    esac
done

cargo_args=()
if $check; then
    echo "Running formatters in check mode..."
    cargo_args=("--check")
elif $fix; then
    echo "Running formatters in fix mode..."
else
    echo "Must specify either --check or --fix"
    exit 1
fi

cargo fmt --all "${cargo_args[@]}"