#!/usr/bin/env bash
#/ Usage: script/reset-emulator
#/
#/ Resets the emulator to a clean state.
script_dir=$(dirname "$(readlink -f "$0")")
cd "$script_dir/.."

echo "Stopping emulator..."
docker compose down

echo "Starting emulator..."
script/start-emulator
