/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function enableTracing(): void
export declare function version(): string
export declare class QueryPipeline {
  constructor()
}
