// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.


/* Generated with cbindgen:0.28.0 */

// This file is generated by cbindgen. Do not edit it directly.


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Returns the version of the Cosmos Client Engine in use.
 */
const char *cosmoscx_version(void);
